//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : bar.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//

#include "shape.h"

#if !defined(_BOX_H)
#define _BOX_H



class Bar :public Shape 
{
public:
	Bar();
	void Draw();
};

#endif  //_BOX_H
