//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Circle.h
//  @ Date : 3/3/2011
//  @ Author : Andrey Shamis Ilia Gaysinski
//
//


#if !defined(_CIRCLE_H)
#define _CIRCLE_H
#define _USE_MATH_DEFINES
#include "shape.h"
#include <math.h>

#define DEFAULT_RADIUS 0.1
class Circle : public Shape
{
public:
	Circle(float x, float y,RgbColor &color, bool isEmpty);
	void Draw();
private:
	bool _isEmpty;
};

#endif  //_CIRCLE_H
