//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Cycle.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_CYCLE_H)
#define _CYCLE_H


class Cycle
{
};

#endif  //_CYCLE_H
