//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Paint.cpp
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#include "Paint.h"

Paint::Paint()
{
	glMatrixMode(GL_PROJECTION);  
    glLoadIdentity();
    gluOrtho2D(0, 500, 0, 500);
}

void Paint::display()
{
	glClear(GL_COLOR_BUFFER_BIT ); 
	for(int i=0;i<(int)_obj.size();i++)
		_obj[i]->Draw();

	glFlush() ; 
	glutSwapBuffers();
}

void Paint::selectFromMenu(const int &id)
{
;
}

void Paint::idle()
{
	static int x;
	if(x != 10)
	{
		x = 10;
		Bar *bar;
		Circle *cir,*cir_nohole;
		bar = new  Bar(120,130);
		cir = new Circle(0.8,0.2,true);
		cir_nohole = new Circle(0.6,0.7,false);
		cout << "Create \n";
		_obj.push_back(cir);
		_obj.push_back(bar);
		_obj.push_back(cir_nohole);

	}
}
void Paint::mouseButton(const int &button,const int &state, const float &x , const float &y)
{
	cout << "Button:" << button << " State:" << state << " X:"<<x<<" Y:"<<y << "\n";

}
void Paint::ShowMenu()
{
;
}

void Paint::DrowByStatus()
{
;
}

