//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Paint.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_PAINT_H)
#define _PAINT_H

#include "Figures.h"
#include <vector>

using namespace std;

class Paint 
{
public:
	vector < Figures *> _obj;
	vector <_obj *> _objs;
	vector <Figures *> _undo_redo_obj;
	int menu_status;
	void Paint();
	void ShowMenu();
	void DrowByStatus();
	void display();
	void mouseButton();
	void idle();
	void selectFromMenu();
private:
	vector <UndoRedoFigures*>  _undo_redo;
};

#endif  //_PAINT_H
