//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Paint.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_PAINT_H)
#define _PAINT_H
#include <vector>			
#include "Box.h"
#include "Cycle.h"


using namespace std;

struct UndoRedoFigures
{
	Figures *_old;
	Figures *_real;
};


class Paint 
{
public:
	vector <Figures *> _obj;
	//vector <_obj *> _objs;
	vector <Figures *> _undo_redo_obj;
	int menu_status;
	Paint();
	void ShowMenu();
	void DrowByStatus();
	void display();
	void mouseButton(const int &button,const int &state, const float &x , const float &y);
	void idle();
	void selectFromMenu(const int &id);
private:
	vector <UndoRedoFigures>  _undo_redo;
};

#endif  //_PAINT_H
