//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Untitled
//  @ File Name : Paint1.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_PAINT1_H)
#define _PAINT1_H

#include "UndoRedoFigures.h"

class Paint1 : public UndoRedoFigures
{
public:
	int vector < Figures *> _obj;;
	int vector <_obj *> _objs;;
	int vector <Figures *> _undo_redo_obj;;
	int int menu_status;
	void Paint();
	void void ShowMenu();
	void void DrowByStatus();
private:
	int vector <UndoRedoFigures*>  _undo_redo;;
};

#endif  //_PAINT1_H
