//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Shape.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_SHAPE_H)
#define _SHAPE_H


class Shape
{
public:
	Shape();
	virtual void Draw()=0;

protected:
	double _x;
	double _y;
};

#endif  //_SHAPE_H
