//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Shape.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_SHAPE_H)
#define _SHAPE_H


class Shape
{
	Shape();
};

#endif  //_SHAPES_H
