//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Shape.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//
#include "macros.h"

#if !defined(_SHAPE_H)
#define _SHAPE_H



class Shape
{
public:
	Shape();
	virtual void Draw()=0;
	void IncreaseSize(const float &bySize);
	void ShrinkSize(const float &bySize);
protected:
	float _x;
	float _y;
	float _size;
	RgbColor _color;
};

#endif  //_SHAPE_H
