//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Circle.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_WHEEL_H)
#define _WHEEL_H
#define _USE_MATH_DEFINES
#include "shape.h"
#include <math.h>
#include "macros.h"

#define DEFAULT_RADIUS 0.1
class Wheel : public Shape
{
public:
	Wheel(float x,float y);
	void Draw();
};

#endif  //_WHEEL_H
