//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Untitled
//  @ File Name : Box.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_BOX_H)
#define _BOX_H


class Box
{
};

#endif  //_BOX_H
