//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Circle.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_CIRCLE_H)
#define _CIRCLE_H
#include "shape.h"
#include <math.h>
#include "macros.h"

class Circle : public Shape
{
public:
	Circle(float x,float y);
	void Draw();
};

#endif  //_CIRCLE_H
