//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : bar.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//

#include "shape.h"

#if !defined(_EQUIANGULAR_H)
#define _EQUIANGULAR_H

#define DEFAULT_SIZE_SH 0.2

class Equiangular :public Shape 
{
public:
	Equiangular(float x, float y);
	void Draw();
};

#endif  //_EQUIANGULAR_H
