//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Untitled
//  @ File Name : Figures.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_FIGURES_H)
#define _FIGURES_H


class Figures
{
};

#endif  //_FIGURES_H
