//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : bar.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//

#include "shape.h"

#if !defined(_HORIZONTAL_H)
#define _HORIZONTAL_H

#define DEFAULT_SIZE 0.2f

class Horizontal :public Shape 
{
public:
	Horizontal(float x, float y);
	void Draw();
};

#endif  //_HORIZONTAL_H
