//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Untitled
//  @ File Name : Paint1.cpp
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#include "Paint1.h"

void Paint1::Paint()
{

}

void Paint1::void ShowMenu()
{

}

void Paint1::void DrowByStatus()
{

}

