//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Untitled
//  @ File Name : Paint.h
//  @ Date : 3/3/2011
//  @ Author : 
//
//


#if !defined(_PAINT_H)
#define _PAINT_H



class Paint 
{
public:
	int vector < Figures *> _obj;;
	int vector <_obj *> _objs;;
	int vector <Figures *> _undo_redo_obj;;
	int int menu_status;
	void Paint();
	void void ShowMenu();
	void void DrowByStatus();
private:
	int vector <UndoRedoFigures*>  _undo_redo;;
};

#endif  //_PAINT_H
