//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Paint.cpp
//  @ Date : 3/3/2011
//  @ Author : 
//
//

#include "Paint.h"

using namespace std;
Paint::Paint()
{

}

void Paint::display()
{
	for(int i=0;i<(int)_obj.size();i++)
	{
		_obj[i]->Drow();
	}
}

void Paint::selectFromMenu(const int &id)
{
;
}

void Paint::idle()
{
;
}
void Paint::mouseButton(const int &button,const int &state, const float &x , const float &y)
{
	
	cout << button << " - " << state << " - " << x << " - " << y << "\n";
	if(button == 0 && state == 1)
		ShowMenu();
}
void Paint::ShowMenu()
{
	

	
}

void Paint::DrowByStatus()
{
;
}

