//
//
//  Generated by Andrey Shamis Ilia Gaysinski
//
//  @ Project : Paint
//  @ File Name : Paint.cpp
//  @ Date : 3/3/2011
//  @ Author : 
//
//
#include "Paint.h"
Paint::Paint()
{
	glMatrixMode(GL_PROJECTION);  
    glLoadIdentity();
    gluOrtho2D(0, 500, 0, 500);
}

void Paint::display()
{
	glClear(GL_COLOR_BUFFER_BIT ); 
	for(int i=0;i<(int)_obj.size();i++)
		_obj[i]->Draw();

	glFlush() ; 
	glutSwapBuffers();
}

void Paint::selectFromMenu(const int &id)
{
;
}

void Paint::idle()
{
	//	Rectangle *emRectangl=NULL;
	//	Rectangle *pectan=NULL;
		Horizontal *horizonta;
		Vertical *vertica;
		Square *squer;
		Circle *cir,*cir_nohole;
		Wheel *weel;
	static int x;
	if(x != 10)
	{
		x = 10;

		horizonta = new Horizontal(0.4,0.5);
		vertica = new Vertical(0.5,0.4);
		squer = new  Square(0.1,0.1);
		weel = new  Wheel(0.2,0.8);
		//rectangl = new Rectangle(0.2,5.0,false);
		//emRectangl = new Rectangle(0.6,5.0,true);
		cir = new Circle(0.8,0.2,false);
		cir_nohole = new Circle(0.8,0.8,true);
		cout << "Create \n";
		_obj.push_back(cir);
		_obj.push_back(squer);
		_obj.push_back(cir_nohole);
		_obj.push_back(weel);
		_obj.push_back(horizonta);
		_obj.push_back(vertica);
	//	_obj.push_back(emRectangl);
	//	_obj.push_back(rectangl);

	}
}
void Paint::mouseButton(const int &button,const int &state, const float &x , const float &y)
{
	cout << "Button:" << button << " State:" << state << " X:"<<x<<" Y:"<<y << "\n";

}
void Paint::ShowMenu()
{
;
}

void Paint::DrowByStatus()
{
;
}

